### ISSUE TITLE
How to use with modern React

### ISSUE THREAD

**Issue by Dupflo** [TagCommander/react-tag-commander#24]
Is there a way to import react-tag-commander with modern React Hooks ?

I tried on my next.js app but got this error 

```js 

import React, { useState, useEffect } from 'react'

function MyApp() {
  const wrapper = TC_Wrapper.getInstance();

  let [state, setState] = useState({ tcReady: false})

  useEffect(()  => {
    Promise.all([
      wrapper.addContainer("container_head", "/tag-commander-head.js", "head"),
      wrapper.addContainer("container_body", "/tag-commander-body.js", "body"),
    ]).then(() => {
      setState({tcReady: true})
    });
  }, [])


```

But got SyntaxError: Cannot use import statement outside a module

**Comment by RomainLK** [comment]
This is a problem from using Next which doesn't support ES modules. While we evaluate a CJS build, you may use https://github.com/martpie/next-transpile-modules

```
// next.config.js
const withTM = require('next-transpile-modules')(['react-tag-commander']); // pass the modules you would like to see transpiled

module.exports = withTM(); 
```

**Comment by Dupflo** [comment]
Thanks it works perfectly 

However, I have console.log such as "Conteneur Head" or "Conteneur Media", can you tell me how I can remove it ?
